source "https://rubygems.org"

gem "railties"

group :test do
  gem 'diff-lcs' # dependency of RSpec
  gem 'rspec'
end
# Specify your gem's dependencies in visual_crossing_api.gemspec.
gemspec

# Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
#gem "rubocop-rails-omakase", require: false

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"
